Swap to attrs
NASA-AMMOS/aerie-cli pull request #32
Opened 2023-06-21 18:04 UTC by Navarro-Jonathan

2023-06-27 21:33 UTC, cartermak commented
Looking through the supported Ubuntu versions for each Python version, I think we should use `ubuntu-20.04` (latest LTS that supports Python 3.6) instead of `ubuntu-latest` to get 3.6 working. Also, since we're getting specific, let's pin the version to "3.6.8" instead of just 3.6.

2023-06-27 21:42 UTC, Navarro-Jonathan commented
> Looking through the supported Ubuntu versions for each Python version, I think we should use `ubuntu-20.04` (latest LTS that supports Python 3.6) instead of `ubuntu-latest` to get 3.6 working. Also, since we're getting specific, let's pin the version to "3.6.8" instead of just 3.6.

Sure thing. I've made those changes in daea09c

2023-07-18 21:54 UTC, cartermak commented
Unfortunately, this version of pandas/numpy is failing to build (without some clang/C++ configuring) on my M1 Mac.

2023-07-28 17:04 UTC, cartermak requested changes
Mostly looks great, but comments checking on a couple of details

2023-07-31 18:36 UTC, Navarro-Jonathan commented on src/aerie_cli/schemas/api.py
> +def serialize_timedelta_to_postgress(inst, field, value):
This has been fixed in [c0cd0cb](https://github.com/NASA-AMMOS/aerie-cli/pull/32/commits/c0cd0cb26ef495b8c57f76ce3c4df2f9b649dddd)

2023-07-31 18:37 UTC, Navarro-Jonathan commented on src/aerie_cli/schemas/api.py
> +def convert_to_time_delta(t) -> timedelta:
It is now documented in [89276b0](https://github.com/NASA-AMMOS/aerie-cli/pull/32/commits/89276b0515aa9a219958987d17610bf48db0ac9e)

2023-07-31 18:38 UTC, Navarro-Jonathan commented on src/aerie_cli/schemas/api.py
> +        return cls(**json.loads(dictionary))
Yes, they should have been Dict from typing instead. I've changed it in [f2dce67](https://github.com/NASA-AMMOS/aerie-cli/pull/32/commits/f2dce67906ac9d01ba33f90af181634379aa9ae5)

2023-07-31 21:31 UTC, Navarro-Jonathan commented on src/aerie_cli/schemas/api.py
> +        converter = lambda ts: "{" + ",".join(ts) + "}"
That's a good point, I flipped the encoding/decoding there. It should be fixed in [de613ca](https://github.com/NASA-AMMOS/aerie-cli/pull/32/commits/de613ca2749ad0591aa139a5c3943fbd62f5b1bd)

2023-08-10 17:24 UTC, cartermak commented
Need to pull `summary` from this query. Are integration tests downloading constraints from Aerie>1.7?)

https://github.com/NASA-AMMOS/aerie-cli/blob/5b0d373877b1fc76d42b73f7dbff0ea33eb38833/src/aerie_cli/aerie_client.py#L1631

2023-08-10 18:18 UTC, cartermak requested changes

2023-08-15 20:45 UTC, cartermak approved these changes
Nice work! Let's get this merged in and continue testing/considering any further data class changes we want to make.

2023-08-15 20:50 UTC, merged