Improve tests
NASA-AMMOS/aerie-cli pull request #66
Opened 2023-08-08 17:03 UTC by Navarro-Jonathan

2023-08-15 17:24 UTC, cartermak commented
Closes #21

2023-08-23 18:59 UTC, cartermak requested changes
Looks good other than a couple notes. I'm tracking ideas for possible improvements in #62

2023-08-23 19:29 UTC, Navarro-Jonathan commented on tests/integration_tests/test_plans.py
> +    assert "Duplicate activity plan created" in result.stdout
I've removed the duplicate duplicate in [5ad9dab](https://github.com/NASA-AMMOS/aerie-cli/pull/66/commits/5ad9dab69265bdab06463e9fd071e6cb22698445)

2023-08-23 20:32 UTC, Navarro-Jonathan commented on tests/integration_tests/test_scheduling.py
> +        input=str(model_id) + "\n" + str(sim_id) + "\n" + GOAL_PATH + "\n",
This has now been changed in [62beee6](https://github.com/NASA-AMMOS/aerie-cli/pull/66/commits/62beee6e518ee8cacc70f70cdc6c34a45a6c2a5a)

2023-08-23 20:35 UTC, cartermak approved these changes

2023-08-23 20:57 UTC, merged